version: "3"
services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "${WEB_HTTP_PORT:-80}:80"
            - "${WEB_HTTPS_PORT:-443}:443"
        depends_on:
            - php
        working_dir: /var/www/html
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        networks:
            - app
        env_file:
            - .env

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
        networks:
            - app
        env_file:
            - .env

    db:
        image: postgres:13.0
        ports:
            - "${DB_PORT:-5433}:5432"
        environment:
            - POSTGRES_USER=app
            - POSTGRES_DATABASE=app
            - POSTGRES_PASSWORD=pass
            - PGDATA=/var/lib/postgresql/pgdata
        volumes:
            - ./docker/postgres/db_data/pgsql-bkp:/var/bkp
            - ./docker/postgres/db_data/pgsql-data:/var/lib/postgresql/pgdata/
            - ./:/app
        working_dir: /app
        networks:
            - app

networks:
    app:
