FROM nginx

RUN usermod -u 1000 nginx &&  \
    groupmod -g 1000 nginx &&  \
    mkdir -p /var/www/html &&  \
    chown -R nginx:nginx /var/www/html &&  \
    chmod -R 755 /var/www/html && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d && \
    touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid

#USER nginx

WORKDIR /var/www/html